In [ ]:
# câu 1 a 
import numpy as np

# Định nghĩa các vector và ma trận
A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])
C = np.array([[1, 2, -1],
              [0, 3, 4],
              [2, -1, 0]])

# a) Tính tổng A + B và tích số 3A - 2B

# Tính tổng A + B
sum_AB = A + B
print("Tổng A + B là:", sum_AB)

# Tính tích số 3A - 2B
result_3A_2B = 3 * A - 2 * B
print("Tích số 3A - 2B là:", result_3A_2B)

Tổng A + B là: [3 3 1 5]
Tích số 3A - 2B là: [  4 -11  13 -10]


In [ ]:
#câu 1 b
import numpy as np

# Định nghĩa các vector
A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])

# b) Tính tích vô hướng A · B và góc giữa hai vector
dot_product_AB = np.dot(A, B)
print("Tích vô hướng A · B là:", dot_product_AB)
norm_A = np.linalg.norm(A)
norm_B = np.linalg.norm(B)
if norm_A == 0 or norm_B == 0:
    print("Không thể tính góc nếu một trong các vector có độ dài bằng 0.")
else:
    cos_theta = dot_product_AB / (norm_A * norm_B)
    cos_theta = np.clip(cos_theta, -1.0, 1.0)
    theta_rad = np.arccos(cos_theta)
    theta_deg = np.degrees(theta_rad)
    theta_deg_rounded = round(theta_deg, 3)
    print("Góc giữa hai vector A và B là (độ):", theta_deg_rounded)

Tích vô hướng A · B là: -8
Góc giữa hai vector A và B là (độ): 108.376


In [ ]:
# câu 1 c
import numpy as np
C = np.array([[1, 2, -1],
              [0, 3, 4],
              [2, -1, 0]])
C_transpose = C.T
print("Ma trận chuyển vị C^T là:\n", C_transpose)
product_CTC = np.dot(C_transpose, C)
print("Tích ma trận C^T C là:\n", product_CTC)

Ma trận chuyển vị C^T là:
 [[ 1  0  2]
 [ 2  3 -1]
 [-1  4  0]]
Tích ma trận C^T C là:
 [[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]


In [ ]:
#câu 2 a 
import numpy as np

# Định nghĩa các ma trận M và N
M = np.array([[1, 2, 3, 0],
              [4, 5, 6, 1],
              [7, 8, 9, 2],
              [0, 1, 1, 0]])

N = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11],
              [12, 13, 14, 15]])

# a) Tính tích ma trận M × N

product_MN = np.dot(M, N)
print("Tích ma trận M × N là:\n", product_MN)

Tích ma trận M × N là:
 [[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]


In [7]:
# cau 2b
import numpy as np

# Định nghĩa ma trận M
M = np.array([[1, 2, 3, 0],
              [4, 5, 6, 1],
              [7, 8, 9, 2],
              [0, 1, 1, 0]])

# b) Tính định thức của ma trận M
rows, cols = M.shape
if rows != cols:
    print("Không thể tính định thức vì ma trận M không phải là ma trận vuông.")
else:
    determinant_M = np.linalg.det(M)
    print("Định thức của ma trận M là:", determinant_M)

Định thức của ma trận M là: 6.66133814775094e-16


In [8]:
# câu 2c
import numpy as np
N = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11],
              [12, 13, 14, 15]])

# c) Tính hạng của ma trận N

rank_N = np.linalg.matrix_rank(N)
print("Hạng của ma trận N là:", rank_N)

Hạng của ma trận N là: 2


In [19]:
# câu 3 aa
import numpy as np

# Định nghĩa ma trận P
P = np.array([[2, 1, 0, 1],
              [0, 3, 1, -1],
              [1, 0, 4, 2],
              [0, 1, 0, 3]])

# Tính định thức để kiểm tra khả nghịch
det_P = np.linalg.det(P)
print(f"Định thức của ma trận P: {det_P:.2f}")

if det_P != 0:
    P_inv = np.linalg.inv(P)
    print("Ma trận nghịch đảo của P:")
    print(P_inv)
else:
    print("Ma trận P không khả nghịch vì định thức bằng 0")

Định thức của ma trận P: 86.00
Ma trận nghịch đảo của P:
[[ 0.48837209 -0.09302326  0.02325581 -0.20930233]
 [ 0.03488372  0.27906977 -0.06976744  0.12790698]
 [-0.11627907  0.06976744  0.23255814 -0.09302326]
 [-0.01162791 -0.09302326  0.02325581  0.29069767]]


In [ ]:
#câu 3 b

# Vector hằng số
b = np.array([4, 7, 9, 5])

# Giải hệ phương trình Px = b bằng nghịch đảo ma trận
if det_P != 0:
    x = np.dot(P_inv, b)
    print("\nNghiệm của hệ phương trình:")
    print(f"x = {x[0]:.2f}")
    print(f"y = {x[1]:.2f}")
    print(f"z = {x[2]:.2f}")
    print(f"w = {x[3]:.2f}")
else:
    print("Không thể giải hệ phương trình vì ma trận P không khả nghịch")


Nghiệm của hệ phương trình:
x = 0.47
y = 2.10
z = 1.65
w = 0.97


In [ ]:
#câu 3 c
if det_P != 0:
    # Tính P nhân với vector nghiệm
    b_check = np.dot(P, x)
    
    print("\nKiểm tra nghiệm:")
    print("Vector hằng số ban đầu:", b)
    print("Vector tính được từ nghiệm:", b_check)
    
    # Kiểm tra sai số
    error = np.linalg.norm(b - b_check)
    print(f"Sai số: {error:.10f}")
    
    if error < 1e-10:
        print("Nghiệm chính xác")
    else:
        print("Nghiệm có sai số đáng kể")
else:
    print("Không thể kiểm tra nghiệm vì ma trận P không khả nghịch")


Kiểm tra nghiệm:
Vector hằng số ban đầu: [4 7 9 5]
Vector tính được từ nghiệm: [4. 7. 9. 5.]
Sai số: 0.0000000000
Nghiệm chính xác


In [13]:
# câu 4 a
import numpy as np

# Định nghĩa ma trận Q
Q = np.array([[4, -1, 0],
              [1, 3, -2],
              [0, 1, 2]])

# Tính các giá trị riêng
eigenvalues = np.linalg.eigvals(Q)
print("Các giá trị riêng của ma trận Q:")
for i, val in enumerate(eigenvalues, 1):
    print(f"λ{i} = {val:.4f}")

Các giá trị riêng của ma trận Q:
λ1 = 3.4534+0.0000j
λ2 = 2.7733+1.4677j
λ3 = 2.7733-1.4677j


In [ ]:
# 4 b
# Tính cả giá trị riêng và vector riêng
eigenvalues, eigenvectors = np.linalg.eig(Q)

print("\nCác vector riêng tương ứng:")
for i in range(len(eigenvalues)):
    print(f"Vector riêng ứng với λ{i+1} = {eigenvalues[i]:.4f}:")
    print(eigenvectors[:, i])


Các vector riêng tương ứng:
Vector riêng ứng với λ1 = 3.4534+0.0000j:
[0.83327121+0.j 0.455468  +0.j 0.31338154+0.j]
Vector riêng ứng với λ2 = 2.7733+1.4677j:
[-0.26206044-0.31354813j -0.78166743+0.j         -0.21963176+0.41685708j]
Vector riêng ứng với λ3 = 2.7733-1.4677j:
[-0.26206044+0.31354813j -0.78166743-0.j         -0.21963176-0.41685708j]


In [16]:
#c
def normalize_vector(v):
    """Chuẩn hóa vector về độ dài bằng 1"""
    norm = np.linalg.norm(v)
    return v / norm

print("\nCác vector riêng đã chuẩn hóa:")
for i in range(len(eigenvalues)):
    original_vec = eigenvectors[:, i]
    normalized_vec = normalize_vector(original_vec)
    
    print(f"Vector riêng ứng với λ{i+1} = {eigenvalues[i]:.4f} sau chuẩn hóa:")
    print(normalized_vec)
    
    # Kiểm tra độ dài vector đã chuẩn hóa
    norm_check = np.linalg.norm(normalized_vec)
    print(f"Độ dài vector sau chuẩn hóa: {norm_check:.8f}\n")


Các vector riêng đã chuẩn hóa:
Vector riêng ứng với λ1 = 3.4534+0.0000j sau chuẩn hóa:
[0.83327121+0.j 0.455468  +0.j 0.31338154+0.j]
Độ dài vector sau chuẩn hóa: 1.00000000

Vector riêng ứng với λ2 = 2.7733+1.4677j sau chuẩn hóa:
[-0.26206044-0.31354813j -0.78166743+0.j         -0.21963176+0.41685708j]
Độ dài vector sau chuẩn hóa: 1.00000000

Vector riêng ứng với λ3 = 2.7733-1.4677j sau chuẩn hóa:
[-0.26206044+0.31354813j -0.78166743+0.j         -0.21963176-0.41685708j]
Độ dài vector sau chuẩn hóa: 1.00000000



In [ ]:
#câu 5aa
import numpy as np

# Định nghĩa ma trận hệ số R
R = np.array([
    [1, -2, 3],
    [2, 0, 1],
    [-1, 1, 4]
])
b = np.array([10, 8, 7])

print("Ma trận R:")
print(R)
print("\nVector b:")
print(b)

# Giải hệ phương trình Rx = b bằng np.linalg.solve()
try:
    x_solution = np.linalg.solve(R, b)
    print("\nNghiệm của hệ phương trình Rx = b (sử dụng np.linalg.solve()):")
    print(x_solution)
except np.linalg.LinAlgError as e:
    print(f"\nLỗi: {e}")
    print("Ma trận R có thể là ma trận suy biến (không khả nghịch).")

In [17]:
# 5b/
import numpy as np

# Định nghĩa lại ma trận R và vector b từ câu a) nếu chưa chạy lại kernel
R = np.array([
    [1, -2, 3],
    [2, 0, 1],
    [-1, 1, 4]
])
b = np.array([10, 8, 7])

print("Ma trận R:")
print(R)

# Bước 1: Xác định xem ma trận R có khả nghịch không bằng cách tính định thức
det_R = np.linalg.det(R)
print(f"\nĐịnh thức của R (det(R)): {det_R}")

# np.isclose() được dùng để so sánh số thực với 0, tránh lỗi dấu phẩy động
if np.isclose(det_R, 0):
    print("\nMa trận R không khả nghịch vì định thức của nó bằng 0 (hoặc rất gần 0).")
else:
    print("\nMa trận R khả nghịch vì định thức của nó khác 0.")
    R_inv = np.linalg.inv(R)
    print("\nMa trận nghịch đảo của R (R_inv):")
    print(np.around(R_inv, decimals=8)) 

    x_solution_inv = np.dot(R_inv, b)
    print("\nNghiệm của hệ phương trình Rx = b (sử dụng ma trận nghịch đảo):")
    print(np.around(x_solution_inv, decimals=8)) 
    try:
        x_solution_from_solve = np.linalg.solve(R, b) # Tính lại để đảm bảo có biến này
        print("\nSo sánh nghiệm:")
        print(f"Nghiệm từ np.linalg.solve(): {np.around(x_solution_from_solve, decimals=8)}")
        print(f"Nghiệm từ ma trận nghịch đảo:  {np.around(x_solution_inv, decimals=8)}")
        if np.allclose(x_solution_from_solve, x_solution_inv):
            print("\nHai nghiệm hoàn toàn khớp nhau (hoặc rất gần nhau, trong giới hạn sai số dấu phẩy động).")
        else:
            print("\nHai nghiệm có sự khác biệt nhỏ.")
    except NameError:
        print("\nKhông thể so sánh vì nghiệm từ câu a) chưa được tính hoặc biến chưa tồn tại.")

Ma trận R:
[[ 1 -2  3]
 [ 2  0  1]
 [-1  1  4]]

Định thức của R (det(R)): 23.0

Ma trận R khả nghịch vì định thức của nó khác 0.

Ma trận nghịch đảo của R (R_inv):
[[-0.04347826  0.47826087 -0.08695652]
 [-0.39130435  0.30434783  0.2173913 ]
 [ 0.08695652  0.04347826  0.17391304]]

Nghiệm của hệ phương trình Rx = b (sử dụng ma trận nghịch đảo):
[2.7826087  0.04347826 2.43478261]

So sánh nghiệm:
Nghiệm từ np.linalg.solve(): [2.7826087  0.04347826 2.43478261]
Nghiệm từ ma trận nghịch đảo:  [2.7826087  0.04347826 2.43478261]

Hai nghiệm hoàn toàn khớp nhau (hoặc rất gần nhau, trong giới hạn sai số dấu phẩy động).


In [18]:
# 5c
import numpy as np

# Định nghĩa lại ma trận R từ các phần trước
R = np.array([
    [1, -2, 3],
    [2, 0, 1],
    [-1, 1, 4]
])

print("Ma trận R:")
print(R)
frobenius_norm_R = np.linalg.norm(R, 'fro')

print(f"\nChuẩn Frobenius của ma trận R: {frobenius_norm_R}")

sum_of_squares = 0
for row in R:
    for element in row:
        sum_of_squares += element**2
        manual_frobenius_norm = np.sqrt(sum_of_squares)
print(f"Chuẩn Frobenius tính thủ công: {manual_frobenius_norm}")

Ma trận R:
[[ 1 -2  3]
 [ 2  0  1]
 [-1  1  4]]

Chuẩn Frobenius của ma trận R: 6.082762530298219
Chuẩn Frobenius tính thủ công: 6.082762530298219
