####  Câu1:Phép toán cơ bản trên vector và ma trận

In [2]:
# Phần a: Tính tổng A + B và 2A + 3B
import numpy as np

A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])

sum_AB = A + B
linear_comb = 2*A + 3*B

print("a) Kết quả:")
print("A + B =", sum_AB)
print("2A + 3B =", linear_comb)

a) Kết quả:
A + B = [2 3 1 6]
2A + 3B = [ 3 11  2 14]


In [3]:
# b: Tính tích vô hướng và góc giữa A và B
import numpy as np
from numpy.linalg import norm
import math

A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])

dot_product = np.dot(A, B)
cos_theta = dot_product / (norm(A) * norm(B))
angle_deg = math.degrees(math.acos(cos_theta))

print("b) Kết quả:")
print("A · B =", dot_product)
print(f"Góc giữa A và B = {angle_deg:.3f}°")

b) Kết quả:
A · B = -5
Góc giữa A và B = 99.594°


In [4]:
# c: Tính CC^T
import numpy as np

C = np.array([[2, -1, 3],
              [1, 4, -2],
              [0, 2, 5]])

C_transpose = C.T
CC_transpose = np.dot(C, C_transpose)

print("c) Kết quả:")
print("CC^T =")
print(CC_transpose)

c) Kết quả:
CC^T =
[[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]


#### Câu2: Nhân ma trận,định thức và hạng ma trận

In [5]:
import numpy as np
M = np.array([
    [2, -1, 3, 0],
    [1, 4, -2, 5],
    [0, 2, 6, -3],
    [-1, 0, 1, 4]
])

N = np.array([
    [1, 3, -2, 0],
    [4, -1, 5, 2],
    [0, 2, 3, -1],
    [-3, 1, 0, 4]
])

# a) Tính tích M × N 
MN = np.dot(M, N)
print("a) Tích ma trận M × N:")
print(MN)

# b) Tính định thức của M 
det_M = np.linalg.det(M)
print("\nb) Định thức của M:")
if np.isfinite(det_M):
    print(f"{det_M:.2f} (Ma trận khả nghịch vì det ≠ 0)")
else:
    print("0 (Ma trận không khả nghịch)")

# c) Tính hạng của N 
rank_N = np.linalg.matrix_rank(N)
print(f"\nc) Hạng của ma trận N: {rank_N}")

a) Tích ma trận M × N:
[[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]

b) Định thức của M:
409.00 (Ma trận khả nghịch vì det ≠ 0)

c) Hạng của ma trận N: 4


#### Câu3: Nghịch đảo ma trận và giải hệ phương trìnhh


In [7]:
import numpy as np
P = np.array([
    [3, -1, 0, 2],
    [1, 4, -2, 0],
    [0, 1, 5, -1],
    [2, 0, 1, 3]
])
b = np.array([6, 8, 3, 7])  

# a) Tìm ma trận nghịch đảo của P 
try:
    P_inv = np.linalg.inv(P)
    print("a) Ma trận nghịch đảo của P:")
    print(np.round(P_inv, 4))  # Làm tròn 4 chữ số thập phân
except np.linalg.LinAlgError:
    print("a) Ma trận P không khả nghịch do định thức bằng 0")

# b) Giải hệ phương trình bằng nghịch đảo ma trận 
if 'P_inv' in locals():
    x = np.dot(P_inv, b)
    print("\nb) Nghiệm của hệ phương trình [x, y, z, w]:")
    print(np.round(x, 4))
else:
    print("\nb) Không thể giải hệ do ma trận P không khả nghịch")

# c) Kiểm tra nghiệmm
if 'x' in locals():
    check = np.dot(P, x)
    print("\nc) Kiểm tra nghiệm (P × x):")
    print(np.round(check, 4))
    print("Vector hằng số b:", b)
    print("Kết quả khớp:", np.allclose(check, b, atol=1e-4))
else:
    print("\nc) Không thể kiểm tra nghiệm do không có nghiệm")

a) Ma trận nghịch đảo của P:
[[ 0.5     0.1     0.1    -0.3   ]
 [-0.1429  0.2     0.0571  0.1143]
 [-0.0357 -0.05    0.1643  0.0786]
 [-0.3214 -0.05   -0.1214  0.5071]]

b) Nghiệm của hệ phương trình [x, y, z, w]:
[2.     1.7143 0.4286 0.8571]

c) Kiểm tra nghiệm (P × x):
[6. 8. 3. 7.]
Vector hằng số b: [6 8 3 7]
Kết quả khớp: True


####  Câu4: Giá trị riêng,vector riêng và chuẩn hóa

In [ ]:
import numpy as np

# Định nghĩa ma trận Q
Q = np.array([
    [5, -2, 1],
    [0, 3, -1],
    [2, 0, 4]
])

#  a) Tìm giá trị riêng ---
eigenvalues = np.linalg.eigvals(Q)
print("a) Các giá trị riêng của Q:")
print(np.round(eigenvalues, 4))

# b) Tìm vector riêng ---
eigenvalues, eigenvectors = np.linalg.eig(Q)
print("\nb) Các vector riêng tương ứng (chưa chuẩn hóa):")
for i in range(len(eigenvalues)):
    print(f"λ = {np.round(eigenvalues[i], 4)}: {np.round(eigenvectors[:, i], 4)}")

# c) Chuẩn hóa vector riêng (độ dài bằng 1) ---
normalized_eigenvectors = eigenvectors / np.linalg.norm(eigenvectors, axis=0)
print("\nc) Các vector riêng đã chuẩn hóa:")
for i in range(len(eigenvalues)):
    print(f"λ = {np.round(eigenvalues[i], 4)}: {np.round(normalized_eigenvectors[:, i], 4)}")

a) Các giá trị riêng của Q:
[6.3553+0.j     2.8223+1.0773j 2.8223-1.0773j]

b) Các vector riêng tương ứng (chưa chuẩn hóa):
λ = (6.3553+0j): [ 0.7485+0.j -0.1894+0.j  0.6356+0.j]
λ = (2.8223+1.0773j): [-0.3742+0.3423j  0.0947+0.5743j  0.6356+0.j    ]
λ = (2.8223-1.0773j): [-0.3742-0.3423j  0.0947-0.5743j  0.6356-0.j    ]

c) Các vector riêng đã chuẩn hóa:
λ = (6.3553+0j): [ 0.7485+0.j -0.1894+0.j  0.6356+0.j]
λ = (2.8223+1.0773j): [-0.3742+0.3423j  0.0947+0.5743j  0.6356+0.j    ]
λ = (2.8223-1.0773j): [-0.3742-0.3423j  0.0947-0.5743j  0.6356-0.j    ]


#### Câu 5 Ứng dụng thực tế-Hệ phương trình và phân tích

In [13]:
import numpy as np

# Định nghĩa ma trận R và vector b
R = np.array([
    [4, -1, 2],
    [1, 3, -2],
    [0, 2, 5]
])
b = np.array([12, 5, 9])

# a) Giải hệ Rx = b bằng np.linalg.solve() ---
try:
    x_solve = np.linalg.solve(R, b)
    print("a) Nghiệm hệ phương trình (dùng np.linalg.solve()):")
    print(np.round(x_solve, 4))
except np.linalg.LinAlgError:
    print("a) Hệ vô nghiệm hoặc vô số nghiệm do ma trận không khả nghịch")

# b) Kiểm tra khả nghịch và giải bằng nghịch đảo ---
det_R = np.linalg.det(R)
if not np.isclose(det_R, 0):
    R_inv = np.linalg.inv(R)
    x_inv = np.dot(R_inv, b)
    print("\nb) Ma trận R khả nghịch. Định thức =", np.round(det_R, 4))
    print("Ma trận nghịch đảo R⁻¹:")
    print(np.round(R_inv, 4))
    print("Nghiệm dùng R⁻¹:", np.round(x_inv, 4))
    print("So sánh nghiệm: Hai nghiệm trùng khớp?", np.allclose(x_solve, x_inv, atol=1e-6))
else:
    print("\nb) Ma trận R không khả nghịch do định thức = 0")

#  c) Tính chuẩn Frobenius của R ---
frobenius_norm = np.linalg.norm(R, 'fro')
print("\nc) Chuẩn Frobenius của R:", np.round(frobenius_norm, 4))

a) Nghiệm hệ phương trình (dùng np.linalg.solve()):
[2.7882 1.5294 1.1882]

b) Ma trận R khả nghịch. Định thức = 85.0
Ma trận nghịch đảo R⁻¹:
[[ 0.2235  0.1059 -0.0471]
 [-0.0588  0.2353  0.1176]
 [ 0.0235 -0.0941  0.1529]]
Nghiệm dùng R⁻¹: [2.7882 1.5294 1.1882]
So sánh nghiệm: Hai nghiệm trùng khớp? True

c) Chuẩn Frobenius của R: 8.0
