### CHƯƠNG 7: KHÔNG GIAN VECTOR VÀ ÁNH XẠ TUYẾN TÍNH (PHẦN 1) 

##### 1. Giới thiệu một số ứng dụng của tích vector (dot product) 

In [1]:
# Tính tích vô hướng giữa từng hàng của ma trận và một vector
import numpy as np

# Khai báo ma trận A và vector V
signals = np.array([[1, 2], [3, 4], [10, 0]])
sample = np.array([3, -1])

# Tính tích vô hướng từng hàng với vector mẫu
result = np.inner(signals, sample)
result


array([ 1,  5, 30])

#### 1.1.Ứng dụng 1 – Nguyên lý tìm nốt nhạc trong chuỗi âm thanh (Audio search) 


In [2]:
import numpy as np

# Dữ liệu đầu vào
A = np.array([0, 0, -1, 2, 3, -1, 0, 1, -1, -1])
search_vector = np.array([0, 1, -1])

# Kích thước
len_A = len(A)
len_search = len(search_vector)

# Tạo ma trận B từ vector A theo sliding window
B = np.array([A[i:i+len_search] for i in range(len_A - len_search + 1)])

# Tính tích vô hướng giữa từng hàng của B với search_vector
C = np.inner(B, search_vector)

# Tìm các vị trí khớp với search_vector
matches = []
target = np.inner(search_vector, search_vector)

for i in range(len(C)):
    if C[i] == target:
        matches.append((i, B[i]))

(len_A, len_search), B, C, matches


((10, 3),
 array([[ 0,  0, -1],
        [ 0, -1,  2],
        [-1,  2,  3],
        [ 2,  3, -1],
        [ 3, -1,  0],
        [-1,  0,  1],
        [ 0,  1, -1],
        [ 1, -1, -1]]),
 array([ 1, -3, -1,  4, -1, -1,  2,  0]),
 [(6, array([ 0,  1, -1]))])

#### 1.2.Ứng dụng 2 – Tạo ảnh mẫu và làm mờ ảnh 

In [7]:
from PIL import Image, ImageDraw

# Mở ảnh gốc
input_image = Image.open('D:\Đại sô tuyến tính\lap7\jack.png')
input_pixels = input_image.load()  # đọc điểm ảnh (pixel)

# Bộ lọc làm mờ 3x3 (box blur)
box_kernel = [[1/9, 1/9, 1/9],
              [1/9, 1/9, 1/9],
              [1/9, 1/9, 1/9]]

kernel = box_kernel
offset = len(kernel) // 2  # = 1 (vì kernel 3x3)

# Tạo ảnh mới có cùng kích thước với ảnh gốc
output_image = Image.new("RGB", input_image.size)
draw = ImageDraw.Draw(output_image)

# Áp dụng làm mờ
for x in range(offset, input_image.width - offset):
    for y in range(offset, input_image.height - offset):
        acc = [0, 0, 0]  # để cộng dồn giá trị R, G, B
        for a in range(len(kernel)):
            for b in range(len(kernel)):
                xn = x + a - offset
                yn = y + b - offset
                pixel = input_pixels[xn, yn]
                acc[0] += pixel[0] * kernel[a][b]
                acc[1] += pixel[1] * kernel[a][b]
                acc[2] += pixel[2] * kernel[a][b]
        # Ghi điểm ảnh mờ vào ảnh đầu ra
        draw.point((x, y), (int(acc[0]), int(acc[1]), int(acc[2])))

# Lưu ảnh kết quả
output_image.save('D:\Đại sô tuyến tính\lap7\jack_lammo.png')
print("Ảnh đã được làm mờ và lưu tại: D:\Đại sô tuyến tính\lap7\jack_lammo.png")


Ảnh đã được làm mờ và lưu tại: D:\Đại sô tuyến tính\lap7\jack_lammo.png


In [1]:
from PIL import Image, ImageDraw

def apply_box_blur(image, kernel):
    input_pixels = image.load()
    offset = len(kernel) // 2
    output_image = Image.new("RGB", image.size)
    draw = ImageDraw.Draw(output_image)

    for x in range(offset, image.width - offset):
        for y in range(offset, image.height - offset):
            acc = [0, 0, 0]
            for a in range(len(kernel)):
                for b in range(len(kernel)):
                    xn = x + a - offset
                    yn = y + b - offset
                    pixel = input_pixels[xn, yn]
                    acc[0] += pixel[0] * kernel[a][b]
                    acc[1] += pixel[1] * kernel[a][b]
                    acc[2] += pixel[2] * kernel[a][b]
            draw.point((x, y), (int(acc[0]), int(acc[1]), int(acc[2])))

    return output_image

# Mở ảnh gốc
input_image = Image.open(r'D:\Đại sô tuyến tính\lap7\jack.png').convert("RGB")

# Kernel box blur 3x3
box_kernel = [[1/9, 1/9, 1/9],
              [1/9, 1/9, 1/9],
              [1/9, 1/9, 1/9]]

# Làm mờ nhiều lần
blurred_image = input_image
for i in range(3):  # Lặp 3 lần để mờ hơn, có thể tăng lên 5–7 lần nếu muốn
    blurred_image = apply_box_blur(blurred_image, box_kernel)

# Lưu ảnh kết quả
blurred_image.save(r'D:\Đại sô tuyến tính\lap7\jack_lammo.png')
print("Ảnh đã được làm mờ nhiều lần và lưu tại: jack_lammo.png")


Ảnh đã được làm mờ nhiều lần và lưu tại: jack_lammo.png


#### BÀI TẬP CHƯƠNG 7 

In [8]:
import numpy as np

# Định nghĩa ma trận kernel Gaussian
# Đây là ma trận 5x5 bạn đã cung cấp, được chuẩn hóa
gaussian_kernel = np.array([
    [1, 4, 6, 4, 1],
    [4, 16, 24, 16, 4],
    [6, 24, 36, 24, 6],
    [4, 16, 24, 16, 4],
    [1, 4, 6, 4, 1]
], dtype=np.float32) / 256.0

# Nếu bạn đang sử dụng một framework hoặc thư viện yêu cầu bạn cung cấp kernel,
# bạn sẽ sử dụng 'gaussian_kernel' này thay cho 'box_kernel' hiện có.

print("Ma trận kernel Gaussian:")
print(gaussian_kernel)

Ma trận kernel Gaussian:
[[0.00390625 0.015625   0.0234375  0.015625   0.00390625]
 [0.015625   0.0625     0.09375    0.0625     0.015625  ]
 [0.0234375  0.09375    0.140625   0.09375    0.0234375 ]
 [0.015625   0.0625     0.09375    0.0625     0.015625  ]
 [0.00390625 0.015625   0.0234375  0.015625   0.00390625]]


In [9]:
import numpy as np

# a. Ma trận kernel "rút xương" thứ nhất
kernel_a = np.array([
    [0, -1, 0],
    [-1, 4, -1],
    [0, -1, 0]
], dtype=np.float32)

# b. Ma trận kernel "rút xương" thứ hai
kernel_b = np.array([
    [-1, -1, -1],
    [-1, 8, -1],
    [-1, -1, -1]
], dtype=np.float32)

print("Ma trận kernel a:")
print(kernel_a)

print("\nMa trận kernel b:")
print(kernel_b)


Ma trận kernel a:
[[ 0. -1.  0.]
 [-1.  4. -1.]
 [ 0. -1.  0.]]

Ma trận kernel b:
[[-1. -1. -1.]
 [-1.  8. -1.]
 [-1. -1. -1.]]
