## 1.2.1. Các phép xử lý với danh sách


In [1]:
# Khởi tạo 2 danh sách
danhsach1 = [1., 3.]
danhsach2 = [5., 7.]

# Ghép nối 2 danh sách
danhsach = danhsach1 + danhsach2
print("Kết quả phép cộng danh sách:", danhsach)
# [1.0, 3.0, 5.0, 7.0]

# Nhân danh sách với 2 (nhân bản)
danhsach_gapdoi = 2 * danhsach
print("Danh sách gấp đôi:", danhsach_gapdoi)
# [1.0, 3.0, 5.0, 7.0, 1.0, 3.0, 5.0, 7.0]

# Cách khác: nhân trực tiếp
print("Kết quả danhsach * 2:", danhsach * 2)
# [1.0, 3.0, 5.0, 7.0, 1.0, 3.0, 5.0, 7.0]

# Phép chia danh sách (không hợp lệ trong Python)
try:
    print("Kết quả danhsach / 2:", danhsach / 2)
except TypeError as e:
    print("Lỗi:", e)
# Lỗi: unsupported operand type(s) for /: 'list' and 'int'


Kết quả phép cộng danh sách: [1.0, 3.0, 5.0, 7.0]
Danh sách gấp đôi: [1.0, 3.0, 5.0, 7.0, 1.0, 3.0, 5.0, 7.0]
Kết quả danhsach * 2: [1.0, 3.0, 5.0, 7.0, 1.0, 3.0, 5.0, 7.0]
Lỗi: unsupported operand type(s) for /: 'list' and 'int'


## Ghép các danh sách bằng lệnh zip: 

In [2]:
# Danh sách các môn học
mon_hoc = ["ToanCC", "DSTT", "ToanRR", "LaptrinhCB"]

# Thứ tự các môn học
thu_tu = [2, 3, 4, 1]

# Điểm số tương ứng
diem_so = [10, 9, 8, 7]

# Ghép 3 danh sách thành danh sách các bộ 3 (tuple)
anh_xa = zip(thu_tu, mon_hoc, diem_so)

# Để xem kết quả, chuyển sang dạng list và in ra
anh_xa = list(anh_xa)
print("Danh sách sau khi zip:")
print(anh_xa)
# [(2, 'ToanCC', 10), (3, 'DSTT', 9), (4, 'ToanRR', 8), (1, 'LaptrinhCB', 7)]

# Chuyển danh sách này thành tập hợp (set)
tap_hop = set(anh_xa)
print("Tập hợp sau khi chuyển:")
print(tap_hop)
# {(3, 'DSTT', 9), (4, 'ToanRR', 8), (1, 'LaptrinhCB', 7), (2, 'ToanCC', 10)}


Danh sách sau khi zip:
[(2, 'ToanCC', 10), (3, 'DSTT', 9), (4, 'ToanRR', 8), (1, 'LaptrinhCB', 7)]
Tập hợp sau khi chuyển:
{(2, 'ToanCC', 10), (3, 'DSTT', 9), (4, 'ToanRR', 8), (1, 'LaptrinhCB', 7)}


In [3]:
# Dữ liệu đã zip từ trước
anh_xa = [(2, 'ToanCC', 10), (3, 'DSTT', 9), (4, 'ToanRR', 8), (1, 'LaptrinhCB', 7)]

# Tách các phần tử trong danh sách anh_xa ra 3 danh sách riêng biệt
lay_TT, lay_monhoc, lay_diem = zip(*anh_xa)

print("Thứ tự:", lay_TT)
print("Môn học:", lay_monhoc)
print("Điểm số:", lay_diem)


Thứ tự: (2, 3, 4, 1)
Môn học: ('ToanCC', 'DSTT', 'ToanRR', 'LaptrinhCB')
Điểm số: (10, 9, 8, 7)


## 2.1. Đặt nhân tử chung và khai triển biểu thức

In [1]:
from sympy import symbols, factor

x, y = symbols('x y')
bieuthuc = x**3 - y**3
ketqua = factor(bieuthuc)
print(ketqua)


(x - y)*(x**2 + x*y + y**2)


In [2]:
from sympy import symbols, expand

x, y = symbols('x y')
bieuthuc = (x - y)*(x**2 + x*y + y**2)
print(expand(bieuthuc))


x**3 - y**3


## 2.2  Thay thế giá trị

In [3]:
from sympy import Symbol

x = Symbol('x')
y = Symbol('y')
bieuthuc = x*x - x*y + y*y
print((bieuthuc))

x**2 - x*y + y**2


In [4]:
from sympy import Symbol

x = Symbol('x')
y = Symbol('y')
bieuthuc = x*x - x*y + y*y

# Thay thế x = 3, y = 2
giatri = bieuthuc.subs({x: 3, y: 2})
print(giatri)
    

7


## Thực hành


In [ ]:
#tình huống 11
from sympy import symbols

# Khai báo biến
x, y = symbols('x y')

# Định nghĩa biểu thức
bieuthuc = x**2 - x*y + y**2

# Thay thế: x = 3, y = x 
giatri = bieuthuc.subs({x:3, y:x}).subs(x, 3)  
# In ra biểu thức sau khi thay
print(giatri)


9


In [ ]:
#tình huống 2

from sympy import symbols

# Khai báo biến
x, y = symbols('x y')

# Định nghĩa biểu thức
bieuthuc = x**2 - x*y + y**2

# Thay thế theo thứ tự: x = y, y = 3
giatri = bieuthuc.subs({x: y, y: 3})

# In kết quả
print(giatri)


9


## 3.1. Một số lệnh cơ bản numpy xử lý vector 

In [9]:
import numpy as np

# Khởi tạo các vector
vec1 = np.array([1., 3., 5.])
vec2 = np.array([2., 4.])
vec3 = np.array([2., 4., 6.])

print(f"vec1 = {vec1}")
print(f"vec2 = {vec2}")
print(f"vec3 = {vec3}")
print("---")

# vec1 * 2
print(f"vec1 * 2 = {vec1 * 2}")

# vec1 * vec1
print(f"vec1 * vec1 (phép nhân Hadamard) = {vec1 * vec1}")

# vec1 / 2
print(f"vec1 / 2 = {vec1 / 2}")

# vec1 + vec1
print(f"vec1 + vec1 = {vec1 + vec1}")

# vec1 + vec2
try:
    print(f"vec1 + vec2 = {vec1 + vec2}")
except ValueError as e:
    print(f"vec1 + vec2: Lỗi - {e}. Lý do: Kích thước của các vector không khớp.")

# vec1 + vec3
print(f"vec1 + vec3 = {vec1 + vec3}")

# vec1 / vec3
print(f"vec1 / vec3 = {vec1 / vec3}")

# vec1 * vec3
print(f"vec1 * vec3 = {vec1 * vec3}")

# 2 * vec1 + 5 * vec3
print(f"2 * vec1 + 5 * vec3 = {2 * vec1 + 5 * vec3}")

vec1 = [1. 3. 5.]
vec2 = [2. 4.]
vec3 = [2. 4. 6.]
---
vec1 * 2 = [ 2.  6. 10.]
vec1 * vec1 (phép nhân Hadamard) = [ 1.  9. 25.]
vec1 / 2 = [0.5 1.5 2.5]
vec1 + vec1 = [ 2.  6. 10.]
vec1 + vec2: Lỗi - operands could not be broadcast together with shapes (3,) (2,) . Lý do: Kích thước của các vector không khớp.
vec1 + vec3 = [ 3.  7. 11.]
vec1 / vec3 = [0.5        0.75       0.83333333]
vec1 * vec3 = [ 2. 12. 30.]
2 * vec1 + 5 * vec3 = [12. 26. 40.]


In [10]:
import numpy as np

# Khai báo vector
v = np.array([1., 3., 5.])
print(f"Vector ban đầu v = {v}")
print("-" * 20)

# Lệnh lấy tổng các thành phần của vector
total_sum = np.sum(v)
print(f"Tổng các thành phần của vector: {total_sum}")
print("-" * 20)

# Lệnh xem số chiều của một vector
vector_shape = v.shape
print(f"Số chiều của vector (v.shape): {vector_shape}")
print("-" * 20)

# Thử nghiệm “chuyển vị” vector
v_transposed = v.transpose()
print(f"Kết quả chuyển vị (v.transpose()): {v_transposed}")
print("Lưu ý: Đối với vector 1D, transpose() không thay đổi hình dạng.")
print("-" * 20)

# Lệnh lấy một phần của vector
v1 = v[:2]
print(f"v1 = v[:2]: {v1}")
print("Lưu ý: v1 là một 'view' của v, không phải bản sao độc lập.")
print("-" * 20)

# Thay đổi giá trị trong v và quan sát v1
v[0] = 5
print(f"Sau khi v[0] = 5, vector v là: {v}")
print(f"Và v1 bây giờ là: {v1}")
print("Giải thích: v1 bị ảnh hưởng vì nó là view của v.")
print("-" * 20)

# Thử gán giá trị không khớp kích thước cho slice
print("Thử gán v1[:2] = [1., 2., 3.] (sẽ gây lỗi):")
try:
    v1[:2] = [1., 2., 3.]
except ValueError as e:
    print(f"Lỗi: {e}")
    print("Lý do: Số lượng phần tử gán (3) không khớp với kích thước slice (2).")
print("-" * 20)

# Gán giá trị khớp kích thước cho slice
v1[:2] = [1., 2.]
print(f"Sau khi v1[:2] = [1., 2.], vector v là: {v}")
print("Giải thích: Thay đổi trên v1 cũng ảnh hưởng đến v.")
print("-" * 20)

Vector ban đầu v = [1. 3. 5.]
--------------------
Tổng các thành phần của vector: 9.0
--------------------
Số chiều của vector (v.shape): (3,)
--------------------
Kết quả chuyển vị (v.transpose()): [1. 3. 5.]
Lưu ý: Đối với vector 1D, transpose() không thay đổi hình dạng.
--------------------
v1 = v[:2]: [1. 3.]
Lưu ý: v1 là một 'view' của v, không phải bản sao độc lập.
--------------------
Sau khi v[0] = 5, vector v là: [5. 3. 5.]
Và v1 bây giờ là: [5. 3.]
Giải thích: v1 bị ảnh hưởng vì nó là view của v.
--------------------
Thử gán v1[:2] = [1., 2., 3.] (sẽ gây lỗi):
Lỗi: could not broadcast input array from shape (3,) into shape (2,)
Lý do: Số lượng phần tử gán (3) không khớp với kích thước slice (2).
--------------------
Sau khi v1[:2] = [1., 2.], vector v là: [1. 2. 5.]
Giải thích: Thay đổi trên v1 cũng ảnh hưởng đến v.
--------------------


In [11]:
import numpy as np

v = np.array([1., 3., 5.])
v1 = v[:2] # v1 lúc này là một view của v, tức là [1., 3.]
print(f"Vector v ban đầu: {v}")
print(f"Vector v1 (view của v[:2]): {v1}")
print("-" * 30)
v3 = 2 * v[:2] + v1 * 3
print(f"Kết quả v3 = 2 * v[:2] + v1 * 3: {v3}")
print("-" * 30)
v1 = [4, 6]
print(f"Sau khi v1 = [4, 6] (v1 trở thành list):")
print(f"v1 bây giờ là: {v1} (kiểu: {type(v1)})")
print("-" * 30)
print(f"Giá trị của v3 (không thay đổi): {v3}")
print("-" * 30)
print(f"Giá trị của v (không thay đổi so với trước khi gán lại v1): {v}")
print("-" * 30)

Vector v ban đầu: [1. 3. 5.]
Vector v1 (view của v[:2]): [1. 3.]
------------------------------
Kết quả v3 = 2 * v[:2] + v1 * 3: [ 5. 15.]
------------------------------
Sau khi v1 = [4, 6] (v1 trở thành list):
v1 bây giờ là: [4, 6] (kiểu: <class 'list'>)
------------------------------
Giá trị của v3 (không thay đổi): [ 5. 15.]
------------------------------
Giá trị của v (không thay đổi so với trước khi gán lại v1): [1. 3. 5.]
------------------------------


In [12]:
import numpy as np

# Khai báo vector v (giả sử giá trị của nó là [1., 3., 5.] như ban đầu)
v = np.array([1., 3., 5.])

print(f"Vector v ban đầu: {v}")
print("-" * 30)

# v + 10.0
result_add_scalar = v + 10.0
print(f"v + 10.0 = {result_add_scalar}")
print("-" * 30)

# np.sqrt(v)
result_sqrt = np.sqrt(v)
print(f"np.sqrt(v) = {result_sqrt}")
print("-" * 30)

# np.cos(v)
result_cos = np.cos(v)
print(f"np.cos(v) = {result_cos}")
print("-" * 30)

# np.sin(v)
result_sin = np.sin(v)
print(f"np.sin(v) = {result_sin}")
print("-" * 30)

Vector v ban đầu: [1. 3. 5.]
------------------------------
v + 10.0 = [11. 13. 15.]
------------------------------
np.sqrt(v) = [1.         1.73205081 2.23606798]
------------------------------
np.cos(v) = [ 0.54030231 -0.9899925   0.28366219]
------------------------------
np.sin(v) = [ 0.84147098  0.14112001 -0.95892427]
------------------------------


In [13]:
import numpy as np

# Khai báo các vector
v1 = np.array([1, 2])
v3 = np.array([3, 4])

print(np.dot(v1, v3))  



11


### BT Chương 11

In [14]:
# bt 1:
from sympy import Symbol, solve, sqrt

# Khai báo biến x
x = Symbol('x')

# Ví dụ 1: Giải phương trình x + 3 = 5
bieuthuc_1 = x + 3 - 5
nghiem_1 = solve(bieuthuc_1)
print("Nghiệm của phương trình x + 3 = 5 là:", nghiem_1)

# Ví dụ 2: Giải phương trình x^2 + 3 = 5
bieuthuc_2 = x**2 + 3 - 5
nghiem_2 = solve(bieuthuc_2)
print("Nghiệm của phương trình x^2 + 3 = 5 là:", nghiem_2)
print("Nghiệm thứ nhất:", nghiem_2[0])
print("Nghiệm thứ hai:", nghiem_2[1])


Nghiệm của phương trình x + 3 = 5 là: [2]
Nghiệm của phương trình x^2 + 3 = 5 là: [-sqrt(2), sqrt(2)]
Nghiệm thứ nhất: -sqrt(2)
Nghiệm thứ hai: sqrt(2)


In [15]:
#bt 2 
from sympy import Symbol, solve, I

# Khai báo biến x
x = Symbol('x')

# Trường hợp 1: Nghiệm thực
ptb2_1 = x**2 + 9*x + 8
nghiem_1 = solve(ptb2_1, dict=True)
print("Nghiệm của phương trình x² + 9x + 8 = 0 là:")
print(nghiem_1)

# Trường hợp 2: Nghiệm phức
ptb2_2 = x**2 + x + 10
nghiem_2 = solve(ptb2_2, dict=True)
print("Nghiệm của phương trình x² + x + 10 = 0 là:")
print(nghiem_2)


Nghiệm của phương trình x² + 9x + 8 = 0 là:
[{x: -8}, {x: -1}]
Nghiệm của phương trình x² + x + 10 = 0 là:
[{x: -1/2 - sqrt(39)*I/2}, {x: -1/2 + sqrt(39)*I/2}]


In [16]:
#bt 3
from sympy import Symbol, solve

# Khai báo các biến
x = Symbol('x')
a = Symbol('a')
b = Symbol('b')
c = Symbol('c')

# Định nghĩa phương trình bậc 2 tổng quát
ptb2 = a*x**2 + b*x + c

# Giải phương trình theo biến x, trả về dưới dạng dict
nghiem = solve(ptb2, x, dict=True)

# In kết quả nghiệm
print("Nghiệm tổng quát của phương trình a*x**2 + b*x + c = 0 là:")
print(nghiem)


Nghiệm tổng quát của phương trình a*x**2 + b*x + c = 0 là:
[{x: (-b - sqrt(-4*a*c + b**2))/(2*a)}, {x: (-b + sqrt(-4*a*c + b**2))/(2*a)}]


In [ ]:
#BT4 
from sympy import Symbol, solve

# Khai báo biến
x = Symbol('x')
y = Symbol('y')

# Định nghĩa hai phương trình
pt1 = 2*x + 3*y - 12
pt2 = 3*x - 2*y - 5

# Giải hệ phương trình và trả về kết quả dạng dictionary
nghiem = solve((pt1, pt2), dict=True)

# In kết quả nghiệm
print("Nghiệm của hệ phương trình là:", nghiem)

# Lấy nghiệm đầu tiên trong danh sách
nghiem0 = nghiem[0]

# Thay nghiệm vào phương trình thứ nhất
ket_qua_pt1 = pt1.subs({x: nghiem0[x], y: nghiem0[y]})
print("Thay nghiệm vào pt1, kết quả:", ket_qua_pt1)

# Thay nghiệm vào phương trình thứ hai
ket_qua_pt2 = pt2.subs({x: nghiem0[x], y: nghiem0[y]})
print("Thay nghiệm vào pt2, kết quả:", ket_qua_pt2)



Nghiệm của hệ phương trình là: [{x: 3, y: 2}]
Thay nghiệm vào pt1, kết quả: 0
Thay nghiệm vào pt2, kết quả: 0


In [18]:
#bt5 
import numpy as np

# Khai báo ma trận M1
M1 = np.array([ [9, 12], [23,30] ])

# In ra M1 để xem kết quả hiển thị trên màn hình
print(M1)

# Bạn cũng có thể kiểm tra kiểu dữ liệu và hình dạng của M1
print(f"Kiểu dữ liệu của M1: {type(M1)}")
print(f"Hình dạng của M1 (số hàng, số cột): {M1.shape}")

[[ 9 12]
 [23 30]]
Kiểu dữ liệu của M1: <class 'numpy.ndarray'>
Hình dạng của M1 (số hàng, số cột): (2, 2)


In [19]:
import numpy as np

# Khai báo ma trận M1 và vector u
M1 = np.array([[1, 2],
               [3, 4]])
u = np.array([2, 1])

# Phép nhân M1.dot(u)
tichM1u = M1.dot(u)
print("M1.dot(u) =", tichM1u)  # Kết quả: [4, 10]

# Phép nhân u.dot(M1)
tichuM1 = u.dot(M1)
print("u.dot(M1) =", tichuM1)  # Kết quả: [5, 8]

# Phép nhân np.dot(M1, u)
print("np.dot(M1, u) =", np.dot(M1, u))  # Kết quả: [4, 10]

# Phép nhân np.dot(u, M1)
print("np.dot(u, M1) =", np.dot(u, M1))  # Kết quả: [5, 8]


M1.dot(u) = [ 4 10]
u.dot(M1) = [5 8]
np.dot(M1, u) = [ 4 10]
np.dot(u, M1) = [5 8]


In [20]:
import numpy as np

# 1. Ma trận toàn số 0
mat1 = np.zeros([5, 5])
print("mat1:\n", mat1)

# 2. Ma trận toàn số 1
mat2 = np.ones([5, 5])
print("mat2:\n", mat2)

# 3. mat3 = mat1 + 2 * mat2
mat3 = mat1 + 2 * mat2
print("mat3:\n", mat3)

# 4. Gán mat4 = mat3, sau đó thay đổi mat3
mat4 = mat3
mat3[3][2] = 10
print("mat3 (sau khi thay đổi [3][2] = 10):\n", mat3)
print("mat4 (có thay đổi theo mat3 không?):\n", mat4)
# Kết luận: mat4 thay đổi vì nó tham chiếu đến cùng vùng nhớ với mat3

# 5. Copy độc lập bằng np.copy()
mat5 = np.copy(mat3)
mat3[3][2] = 10  # thay đổi lại vẫn là 10, không ảnh hưởng đến mat5
print("mat3 (sau khi gán lại 10):\n", mat3)
print("mat4 (cùng vùng nhớ với mat3):\n", mat4)
print("mat5 (sao chép riêng biệt):\n", mat5)
# Kết luận: mat5 KHÔNG bị thay đổi khi mat3 thay đổi

# 6. Ma trận rỗng với giá trị ngẫu nhiên (rác trong RAM)
mat6 = np.empty([4, 5])
print("mat6 (ma trận rỗng - giá trị không xác định):\n", mat6)

# 7. Ma trận đơn vị
mat7 = np.identity(4)
print("mat7 (ma trận đơn vị 4x4):\n", mat7)

# 8. Ma trận ngẫu nhiên (giá trị trong khoảng [0, 1))
mat8 = np.random.random([4, 5])


mat1:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
mat2:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
mat3:
 [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
mat3 (sau khi thay đổi [3][2] = 10):
 [[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2. 10.  2.  2.]
 [ 2.  2.  2.  2.  2.]]
mat4 (có thay đổi theo mat3 không?):
 [[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2. 10.  2.  2.]
 [ 2.  2.  2.  2.  2.]]
mat3 (sau khi gán lại 10):
 [[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2. 10.  2.  2.]
 [ 2.  2.  2.  2.  2.]]
mat4 (cùng vùng nhớ với mat3):
 [[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2. 10.  2.  2.]
 [ 2.  2.  2.  2.  2.]]
mat5 (sao chép riêng biệt):
 [[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2