# BT CHƯƠNG


## 1. Dẫn nhập – Một số hàm về xử lý vector với Python
Trong bài trước, chúng ta thấy rằng chỉ đơn thuần Python có thể hỗ trợ cài đặt các phép xử lý cơ
bản cho vector. Dưới đây, chúng ta tổng kết việc xử lý vector thông qua 4 hàm cơ bản:
Hàm “scale” tỉ số vector bằng một giá trị thực



In [1]:
!pip install numpy



[notice] A new release of pip is available: 23.2.1 -> 25.1.1
[notice] To update, run: C:\Users\Admin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [1]:
def scale(a, v):
    return [a * vi for vi in v]
v = [3, 5, 7]
print(scale(10, v))

[30, 50, 70]


## Hàm lấy tổng hai vector:

In [2]:
def sumvector(v, w):
        return [vi + wi for (vi, wi) in zip(v, w)]
v = [3, 5, 7]
w = [2, 4, 6]
print(sumvector(v, w))

[5, 9, 13]


## Hàm nhân 2 vector vô hướng

In [3]:
def dotvector(v, w):
    return sum([vi * wi for (vi, wi) in zip(v, w)])
v = [3, 5, 7]
w = [2, 4, 6]

print(dotvector(v, w))

68


## Hàm tính chiều dài một vector:

In [4]:
def lenvector(v):
    return dotvector(v, v)
v = [3, 5, 7]
w = [2, 4, 6]
print(lenvector(w))



56


## 2. Bài toán ứng dụng 1 – Phân loại tuyến tính

In [5]:
import numpy as np

# Tạo mảng điểm số
scores = np.array([-1, 1, 2, -3, 5, -4])
print("scores =", scores)

# Kiểm tra điều kiện điểm >= 0
print("scores >= 0:", scores >= 0)

# Kiểm tra điều kiện điểm < 0
print("scores < 0:", scores < 0)

# Phân loại tuyến tính: số âm hoặc số dương
labels = np.select([scores >= 0, scores < 0], ['so duong', 'so am'])
print("Phân loại:", labels)


scores = [-1  1  2 -3  5 -4]
scores >= 0: [False  True  True False  True False]
scores < 0: [ True False False  True False  True]
Phân loại: ['so am' 'so duong' 'so duong' 'so am' 'so duong' 'so am']


In [1]:
import numpy as np

# Tạo mảng điểm số
scores = np.array([-1, 1, 2, 0, -3, 5, 0, -4])
print("Mảng scores:", scores)

# Phân loại giá trị: > 0, == 0, < 0
labels = np.select(
    [scores > 0, scores == 0, scores < 0],
    ['so duong', 'so 0', 'so am']
)

# In kết quả phân loại
print("Kết quả phân loại:", labels)


Mảng scores: [-1  1  2  0 -3  5  0 -4]
Kết quả phân loại: ['so am' 'so duong' 'so duong' 'so 0' 'so am' 'so duong' 'so 0' 'so am']


# 3. Thực hành xử lý ma trận
3.1 Cơ bản xử lý ma trận


In [2]:
import numpy as np
from scipy import linalg, sparse

D = np.mat([[3, 4], [5, 6]])
print(D)


[[3 4]
 [5 6]]


In [6]:
# 1: Nạp thư viện
import numpy as np
from scipy import linalg, sparse  # nạp các module đại số tuyến tính và ma trận thưa

# 2: Tạo ma trận D với giá trị cụ thể
D = np.mat([[3, 4], [5, 6]])
print("STT 2 – Ma trận D:")
print(D)

# 3: Tạo ma trận C ngẫu nhiên kích thước 5x7
C = np.mat(np.random.random((5, 7)))
print("\nSTT 3 – Ma trận C (5x7, ngẫu nhiên):")
print(C)

# 4: Tạo ma trận A ngẫu nhiên kích thước 2x2
A = np.mat(np.random.random((2, 2)))
print("\nSTT 4 – Ma trận A (2x2, ngẫu nhiên):")
print(A)

# 5: Tạo mảng số phức và chuyển thành ma trận
b = np.array([
    [1 + 5j, 2j, 3j],
    [4 + 6j, 5 + 0j, 6]
])
B = np.asmatrix(b)

print("\nSTT 5 – Mảng b:")
print(b)

print("\nSTT 5 – Ma trận B (từ asmatrix):")
print(B)

# In chuyển vị của ma trận A (STT 4)
print("\nSTT 5 – Chuyển vị của ma trận A:")
print(A.T)



#  6: Tính ma trận nghịch đảo A (nếu đã có A từ STT 4)
print("STT 6 – Ma trận nghịch đảo của A (A.I):")
print(A.I)  # A là ma trận từ np.mat

# 7: Sử dụng linalg.inv để tính nghịch đảo của ma trận thường (array)
M = np.array([[-1, 3, 2], [0, -2, 1], [1, 5, -2]])

print("\nSTT 7 – Nghịch đảo của ma trận M (dùng linalg.inv):")
M_inv = linalg.inv(M)
print(M_inv)

#  8: Lấy phần tam giác dưới của ma trận M
M_lower = np.tril(M)
print("\nSTT 8 – Tam giác dưới của M:")
print(M_lower)

# 9: Lấy phần tam giác trên của ma trận M
M_upper = np.triu(M)
print("\nSTT 9 – Tam giác trên của M:")
print(M_upper)

#✅ STT 10 – Trích xuất và tạo ma trận đường chéo



# M đã được khai báo ở STT trước:
M = np.array([[-1, 3, 2], [0, -2, 1], [1, 5, -2]])

# Lấy vector đường chéo chính của ma trận M
v_diag = np.diag(M)
print("STT 10 – Vector đường chéo của M:")
print(v_diag)

# Tạo ma trận đường chéo từ vector v_diag
M_diag = np.diag(v_diag)
print("\nSTT 10 – Ma trận đường chéo tạo từ vector:")
print(M_diag)




STT 2 – Ma trận D:
[[3 4]
 [5 6]]

STT 3 – Ma trận C (5x7, ngẫu nhiên):
[[0.41701535 0.99249242 0.36961277 0.6355932  0.52853638 0.3915227
  0.94330169]
 [0.28669021 0.05666467 0.84954907 0.4653502  0.71194677 0.06574738
  0.39120567]
 [0.25038986 0.57486085 0.63757699 0.70699374 0.9088593  0.79884206
  0.98419772]
 [0.93393421 0.99091529 0.63613661 0.42291542 0.15081104 0.2483032
  0.28640223]
 [0.40025524 0.65317769 0.77872217 0.2360966  0.07078927 0.12823753
  0.75122687]]

STT 4 – Ma trận A (2x2, ngẫu nhiên):
[[0.55900786 0.64443311]
 [0.34788323 0.83995941]]

STT 5 – Mảng b:
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+6.j 5.+0.j 6.+0.j]]

STT 5 – Ma trận B (từ asmatrix):
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+6.j 5.+0.j 6.+0.j]]

STT 5 – Chuyển vị của ma trận A:
[[0.55900786 0.34788323]
 [0.64443311 0.83995941]]
STT 6 – Ma trận nghịch đảo của A (A.I):
[[ 3.42342515 -2.62651799]
 [-1.41786875  2.27835005]]

STT 7 – Nghịch đảo của ma trận M (dùng linalg.inv):
[[-0.125  2.     0.875]
 [ 0.125 -0.     0.125]


In [7]:
import sympy as sp

# Khai báo biến
x = sp.Symbol('x')
y = sp.Symbol('y')
z = sp.Symbol('z')

# Giải hệ phương trình
solution = sp.solve([
    x**2 + 2 - 6,     # x^2 + 2 = 6
    y - 1 - 6,        # y - 1 = 6
    x + z - 1,        # x + z = 1
    2 * x**2 - 8,     # 2x^2 = 8
    z**2 + 4 - 5,     # z^2 + 4 = 5
    y - z - 8         # y - z = 8
], [x, y, z])

print(solution)


[(2, 7, -1)]


# 3.2. Các phép biến đổi sơ cấp trên ma trận

In [9]:
import numpy as np

# Tạo ma trận A kích thước 6x6 với các giá trị từ 0 đến 35
A = np.reshape(np.arange(36.0), (6, 6))
print("Ma trận A:")
print(A)

# Tạo ma trận đơn vị kích thước 6x6
I6 = np.identity(6)
print("\nMa trận đơn vị I6:")
print(I6)

# Tạo ma trận A kích thước 6x6
A = np.reshape(np.arange(36.0), (6, 6))

# Tạo ma trận đơn vị I6
I6 = np.identity(6)

# Kiểm tra số phần tử trong A
print("Kích thước (số phần tử) của A:", A.size)

# In đường chéo chính của A
print("Đường chéo của A:", np.diagonal(A))

# Cộng A với ma trận đơn vị
A = A + I6
print("Ma trận A mới sau khi cộng với I6:")
print(A)



Ma trận A:
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]

Ma trận đơn vị I6:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
Kích thước (số phần tử) của A: 36
Đường chéo của A: [ 0.  7. 14. 21. 28. 35.]
Ma trận A mới sau khi cộng với I6:
[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]


Tính tích (nhân) ma trận với vector (là dạng ma trận đặc biệt)


In [12]:
import numpy as np

# Tạo ma trận A kích thước 6x6
A = np.reshape(np.arange(1, 37), (6, 6))  # Ma trận từ 1 đến 36

# Tạo vector vecB
vecB = np.array([1., 2., 3., 4., 5., 6.])

# Nhân ma trận A với vecB
C = A.dot(vecB)

# In kết quả
print("Ma trận A:")
print(A)
print("\nVector vecB:")
print(vecB)
print("\nKết quả C = A.dot(vecB):")
print(C)


Ma trận A:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Vector vecB:
[1. 2. 3. 4. 5. 6.]

Kết quả C = A.dot(vecB):
[ 91. 217. 343. 469. 595. 721.]


Khai báo ma trận D 2x6

In [11]:
import numpy as np

# Tạo ma trận A 6x6
A = np.reshape(np.arange(1, 37), (6, 6))

# Tạo ma trận D 2x6
D = np.array([
    [1., 2., 3., 4., 5., 6.],
    [1., 0., 1., 0., 1., 0.]
])

# In ma trận D
print("Ma trận D:")
print(D)

# Tính tích A × D.T (vì A là 6x6, D.T là 6x2 => kết quả là 6x2)
E = A.dot(D.T)

# In kết quả E
print("\nKết quả E = A.dot(D.T):")
print(E)


Ma trận D:
[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]

Kết quả E = A.dot(D.T):
[[ 91.   9.]
 [217.  27.]
 [343.  45.]
 [469.  63.]
 [595.  81.]
 [721.  99.]]


Khai báo ma trận D 2x6

In [10]:
import numpy as np

# 1. Xây dựng ma trận F kích thước 6x2
F = np.array([[1., 1.],
              [2., 0.],
              [3., 1.],
              [4., 0.],
              [5., 1.],
              [6., 0.]])

# 3. In ma trận F
print("Ma trận F:")
print(F)
A = np.array([[1., 0., 1., 0., 1., 0.],
              [0., 1., 0., 1., 0., 1.]])
print("\nMa trận A (ví dụ, không có trong đề bài gốc):")
print(A)

# 2. Tính tích vô hướng G = A.dot(F)
G = A.dot(F)

# 4. In ma trận G
print("\nMa trận G (A.dot(F)):")
print(G)


Ma trận F:
[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]

Ma trận A (ví dụ, không có trong đề bài gốc):
[[1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1.]]

Ma trận G (A.dot(F)):
[[ 9.  3.]
 [12.  0.]]


# 4. Bài toán ứng dụng 2 – Tính toán dãy Fibonacci: Con đường tìm đến tỉ số vàng!

In [13]:
import numpy as np
A = np.array([[1, 1],
              [1, 0]])

b = np.array([1, 0])

n = 10

print("Các cặp số Fibonacci được tạo ra:")

for i in range(n):
    b = A.dot(b)
    print(b)

Các cặp số Fibonacci được tạo ra:
[1 1]
[2 1]
[3 2]
[5 3]
[8 5]
[13  8]
[21 13]
[34 21]
[55 34]
[89 55]


# 5. Cơ bản về hệ phương trình tuyến tính và ứng dụng minh họa 

In [ ]:
import sympy as sp
from sympy import Symbol, solve


x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
x4 = Symbol('x4')


pt1 = x4 + 610 - 450 - x1
pt2 = x1 + 400 - x2 - 640
pt3 = x2 + 600 - x3
pt4 = x3 - x4 - 520
nghiem = sp.solve((pt1, pt2, pt3, pt4))

print(nghiem)


{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}


### BT THỰC HÀNH
 

### CÂU 1


In [1]:
import numpy as np

# Vấn đề 1: Tìm điểm giao giữa hai đường thẳng trong R^2
print("Vấn đề 1: Tìm điểm giao giữa hai đường thẳng trong R^2")
A1 = np.array([[1, -1], [2, 3]])
B1 = np.array([-2, 6])
giao_diem_1 = np.linalg.solve(A1, B1)
print(f"Điểm giao nhau là: {giao_diem_1}")
print("-" * 30)

# Vấn đề 2: Tìm giao điểm giữa ba mặt phẳng trong R^3
print("Vấn đề 2: Tìm giao điểm giữa ba mặt phẳng trong R^3")
A2 = np.array([[1, -1, 0], [2, -1, -1], [1, 1, 1]])
B2 = np.array([2, 3, 6])
giao_diem_2 = np.linalg.solve(A2, B2)
print(f"Điểm giao nhau là: {giao_diem_2}")
print("-" * 30)

# Vấn đề 3: Tìm các hệ số đa thức thỏa thỏa các nghiệm
print("Vấn đề 3: Tìm các hệ số đa thức thỏa thỏa các nghiệm")
A3 = np.array([[1, 1, 1], [4, 2, 1], [9, 3, 1]])
B3 = np.array([4, 3, 4])
he_so_da_thuc = np.linalg.solve(A3, B3)
print(f"Các hệ số [a, b, c] là: {he_so_da_thuc}")
print(f"Đa thức là: p(x) = {he_so_da_thuc[0]:.4f}x^2 + {he_so_da_thuc[1]:.4f}x + {he_so_da_thuc[2]:.4f}")
print("-" * 30)

# Vấn đề 4: Tìm các hệ đa thức khi phân rã để tính tích phân
print("Vấn đề 4: Tìm các hệ số khi phân rã phân thức")
A4 = np.array([[1, 0, 1], [1, 1, -2], [-2, 2, 1]])
B4 = np.array([1, -3, 0])
he_so_phan_thuc = np.linalg.solve(A4, B4)
print(f"Các hệ số [a, b, c] là: {he_so_phan_thuc}")
print(f"Phân rã phân thức là: {he_so_phan_thuc[0]:.4f}/(x-1) + {he_so_phan_thuc[1]:.4f}/(x-1)^2 + {he_so_phan_thuc[2]:.4f}/(x+2)")
print("-" * 30)

Vấn đề 1: Tìm điểm giao giữa hai đường thẳng trong R^2
Điểm giao nhau là: [0. 2.]
------------------------------
Vấn đề 2: Tìm giao điểm giữa ba mặt phẳng trong R^3
Điểm giao nhau là: [3. 1. 2.]
------------------------------
Vấn đề 3: Tìm các hệ số đa thức thỏa thỏa các nghiệm
Các hệ số [a, b, c] là: [ 1. -4.  7.]
Đa thức là: p(x) = 1.0000x^2 + -4.0000x + 7.0000
------------------------------
Vấn đề 4: Tìm các hệ số khi phân rã phân thức
Các hệ số [a, b, c] là: [-0.11111111 -0.66666667  1.11111111]
Phân rã phân thức là: -0.1111/(x-1) + -0.6667/(x-1)^2 + 1.1111/(x+2)
------------------------------


### CÂU 2

In [2]:
import sympy

# 1. Định nghĩa các biến ký hiệu
x, y, z, a, b, c = sympy.symbols('x y z a b c')

print("Giải các phương trình bằng SymPy:")
print("-" * 40)


print("Vấn đề 1: Tìm điểm giao giữa hai đường thẳng trong R^2")
eq1_v1 = sympy.Eq(x - y, -2)
eq2_v1 = sympy.Eq(2*x + 3*y, 6)
solution_v1 = sympy.solve((eq1_v1, eq2_v1), (x, y))
print(f"Điểm giao nhau (x, y) là: {solution_v1}")
print("-" * 40)


print("Vấn đề 2: Tìm giao điểm giữa ba mặt phẳng trong R^3")
eq1_v2 = sympy.Eq(x - y, 2)
eq2_v2 = sympy.Eq(2*x - y - z, 3)
eq3_v2 = sympy.Eq(x + y + z, 6)
solution_v2 = sympy.solve((eq1_v2, eq2_v2, eq3_v2), (x, y, z))
print(f"Điểm giao nhau (x, y, z) là: {solution_v2}")
print("-" * 40)

print("Vấn đề 3: Tìm các hệ số đa thức thỏa thỏa các nghiệm")
eq1_v3 = sympy.Eq(a + b + c, 4)
eq2_v3 = sympy.Eq(4*a + 2*b + c, 3)
eq3_v3 = sympy.Eq(9*a + 3*b + c, 4)
solution_v3 = sympy.solve((eq1_v3, eq2_v3, eq3_v3), (a, b, c))
print(f"Các hệ số (a, b, c) là: {solution_v3}")
print(f"Đa thức là: p(x) = {solution_v3[a]}x^2 + {solution_v3[b]}x + {solution_v3[c]}")
print("-" * 40)


print("Vấn đề 4: Tìm các hệ số khi phân rã phân thức")
eq1_v4 = sympy.Eq(a + c, 1)
eq2_v4 = sympy.Eq(a + b - 2*c, -3)
eq3_v4 = sympy.Eq(-2*a + 2*b + c, 0)
solution_v4 = sympy.solve((eq1_v4, eq2_v4, eq3_v4), (a, b, c))
print(f"Các hệ số (a, b, c) là: {solution_v4}")
print(f"Phân rã phân thức là: {solution_v4[a]}/(x-1) + {solution_v4[b]}/(x-1)^2 + {solution_v4[c]}/(x+2)")
print("-" * 40)

Giải các phương trình bằng SymPy:
----------------------------------------
Vấn đề 1: Tìm điểm giao giữa hai đường thẳng trong R^2
Điểm giao nhau (x, y) là: {x: 0, y: 2}
----------------------------------------
Vấn đề 2: Tìm giao điểm giữa ba mặt phẳng trong R^3
Điểm giao nhau (x, y, z) là: {x: 3, y: 1, z: 2}
----------------------------------------
Vấn đề 3: Tìm các hệ số đa thức thỏa thỏa các nghiệm
Các hệ số (a, b, c) là: {a: 1, b: -4, c: 7}
Đa thức là: p(x) = 1x^2 + -4x + 7
----------------------------------------
Vấn đề 4: Tìm các hệ số khi phân rã phân thức
Các hệ số (a, b, c) là: {a: -1/9, b: -2/3, c: 10/9}
Phân rã phân thức là: -1/9/(x-1) + -2/3/(x-1)^2 + 10/9/(x+2)
----------------------------------------


### CÂU 3

In [5]:
import numpy as np
from sympy import Matrix, fibonacci

def calculate_fibonacci_matrix_power(k):

    if k < 0:
        raise ValueError("Bậc lũy thừa k phải là số nguyên không âm.")

    F = np.array([[1, 1],
                  [1, 0]])

    if k == 0:
        return np.array([[1, 0], [0, 1]]) # F^0 là ma trận đơn vị

    F_k = np.linalg.matrix_power(F, k)

    print(f"Ma trận F^{k}:")
    print(F_k)
    print(f"\nKiểm tra các phần tử Fibonacci cho k = {k}:")
    try:
        fibo_k_plus_1 = fibonacci(k + 1)
        fibo_k = fibonacci(k)
        fibo_k_minus_1 = fibonacci(k - 1) if k >= 1 else fibonacci(0) # Fibo_{-1} không xác định trong định nghĩa thông thường

        print(f"Fibo_{k+1} = {fibo_k_plus_1}")
        print(f"Fibo_{k} = {fibo_k}")
        print(f"Fibo_{k-1} = {fibo_k_minus_1} (nếu k >= 1)")

        print("\nSo sánh với các phần tử của ma trận:")
        print(f"F^{k}[0, 0] = {F_k[0, 0]} (mong đợi Fibo_{k+1})")
        print(f"F^{k}[0, 1] = {F_k[0, 1]} (mong đợi Fibo_{k})")
        print(f"F^{k}[1, 0] = {F_k[1, 0]} (mong đợi Fibo_{k})")
        print(f"F^{k}[1, 1] = {F_k[1, 1]} (mong đợi Fibo_{k-1})")

        # Xác nhận các phần tử
        if F_k[0, 0] == fibo_k_plus_1 and \
           F_k[0, 1] == fibo_k and \
           F_k[1, 0] == fibo_k and \
           F_k[1, 1] == fibo_k_minus_1:
            print("\nMa trận F^k chứa đúng các phần tử Fibonacci được mong đợi.")
        else:
            print("\nKiểm tra thất bại. Ma trận F^k không chứa các phần tử Fibonacci được mong đợi.")

    except Exception as e:
        print(f"Lỗi khi tính toán hoặc so sánh Fibonacci: {e}")

    return F_k
print("Thử với k = 1:")
calculate_fibonacci_matrix_power(1)
print("\n" + "="*50 + "\n")

print("Thử với k = 2:")
calculate_fibonacci_matrix_power(2)
print("\n" + "="*50 + "\n")

print("Thử với k = 3:")
calculate_fibonacci_matrix_power(3)
print("\n" + "="*50 + "\n")

print("Thử với k = 5:")
calculate_fibonacci_matrix_power(5)
print("\n" + "="*50 + "\n")

print("Thử với k = 0:") # Trường hợp đặc biệt, F^0 là ma trận đơn vị
calculate_fibonacci_matrix_power(0)
print("\n" + "="*50 + "\n")

Thử với k = 1:
Ma trận F^1:
[[1 1]
 [1 0]]

Kiểm tra các phần tử Fibonacci cho k = 1:
Fibo_2 = 1
Fibo_1 = 1
Fibo_0 = 0 (nếu k >= 1)

So sánh với các phần tử của ma trận:
F^1[0, 0] = 1 (mong đợi Fibo_2)
F^1[0, 1] = 1 (mong đợi Fibo_1)
F^1[1, 0] = 1 (mong đợi Fibo_1)
F^1[1, 1] = 0 (mong đợi Fibo_0)

Ma trận F^k chứa đúng các phần tử Fibonacci được mong đợi.


Thử với k = 2:
Ma trận F^2:
[[2 1]
 [1 1]]

Kiểm tra các phần tử Fibonacci cho k = 2:
Fibo_3 = 2
Fibo_2 = 1
Fibo_1 = 1 (nếu k >= 1)

So sánh với các phần tử của ma trận:
F^2[0, 0] = 2 (mong đợi Fibo_3)
F^2[0, 1] = 1 (mong đợi Fibo_2)
F^2[1, 0] = 1 (mong đợi Fibo_2)
F^2[1, 1] = 1 (mong đợi Fibo_1)

Ma trận F^k chứa đúng các phần tử Fibonacci được mong đợi.


Thử với k = 3:
Ma trận F^3:
[[3 2]
 [2 1]]

Kiểm tra các phần tử Fibonacci cho k = 3:
Fibo_4 = 3
Fibo_3 = 2
Fibo_2 = 1 (nếu k >= 1)

So sánh với các phần tử của ma trận:
F^3[0, 0] = 3 (mong đợi Fibo_4)
F^3[0, 1] = 2 (mong đợi Fibo_3)
F^3[1, 0] = 2 (mong đợi Fibo_3)
F^3[1, 1] = 1 