In [1]:
!pip install numpy 


[notice] A new release of pip is available: 23.2.1 -> 25.1.1
[notice] To update, run: C:\Users\Admin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


### CHƯƠNG 6: CÁC KHÁI NIỆM: KHÔNG GIAN VECTOR,TÍCH TRONG VÀ TRỊ RIÊNG, VECTOR RIÊNG 

### 1. Khái niệm về không gian vector và tích trong

#### 1.1 tóm tắt lý thuyết 


#### 1.2 Tích vô hướng, trực giao và ứng dụng 

In [2]:
# Tích vô hướng (inner product) trong Python bằng NumPy

import numpy as np

# Khởi tạo hai vector một chiều
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Tính tích vô hướng bằng np.inner
tich_inner = np.inner(a, b)
print("Tích vô hướng bằng np.inner(a, b):", tich_inner)

# Tính tích vô hướng bằng np.dot
tich_dot = np.dot(a, b)
print("Tích vô hướng bằng np.dot(a, b):", tich_dot)

# Kiểm tra kết quả có giống nhau không
if tich_inner == tich_dot:
    print("Kết quả giống nhau: np.inner(a, b) == np.dot(a, b) == ", tich_inner)
else:
    print(" Kết quả khác nhau!")



Tích vô hướng bằng np.inner(a, b): 32
Tích vô hướng bằng np.dot(a, b): 32
Kết quả giống nhau: np.inner(a, b) == np.dot(a, b) ==  32


##### Độ dài/chuẩn của vector: 

In [3]:


import numpy as n
a = np.array([1, 2, -3])
chuan_2 = np.linalg.norm(a)  
print("‖a‖₂ (Chuẩn 2) =", chuan_2)
chuan_1 = np.linalg.norm(a, 1)
print("‖a‖₁ (Chuẩn 1) =", chuan_1)
print("✓ Tính tay chuẩn 2: sqrt(1^2 + 2^2 + (-3)^2) = sqrt(14)")
print("✓ Tính tay chuẩn 1: |1| + |2| + |-3| = 6")


‖a‖₂ (Chuẩn 2) = 3.7416573867739413
‖a‖₁ (Chuẩn 1) = 6.0
✓ Tính tay chuẩn 2: sqrt(1^2 + 2^2 + (-3)^2) = sqrt(14)
✓ Tính tay chuẩn 1: |1| + |2| + |-3| = 6


In [ ]:
import math
import numpy as np
from scipy import linalg

def chuan(vector, p):
    return np.sum(np.abs(vector)**p)**(1/p)
a = np.array([1, 2, -3])
print(f"Vector a: {a}\n")


## Chuẩn bậc 1 (Manhattan Norm)
print("--- Chuẩn bậc 1 (Manhattan Norm) ---")
print(f"chuan(a, 1): {chuan(a, 1)}")
print(f"np.linalg.norm(a, 1): {np.linalg.norm(a, 1)}")
print("-" * 30 + "\n")


## Chuẩn bậc 2 (Euclidean Norm)

print("--- Chuẩn bậc 2 (Euclidean Norm) ---")
print(f"chuan(a, 2): {chuan(a, 2)}")
print(f"np.linalg.norm(a, 2): {np.linalg.norm(a, 2)}")
print("-" * 30 + "\n")


## Chuẩn bậc 3

print("--- Chuẩn bậc 3 ---")
print(f"chuan(a, 3): {chuan(a, 3)}")
print(f"np.linalg.norm(a, 3): {np.linalg.norm(a, 3)}")
print("-" * 30 + "\n")


## Chuẩn bậc 1000

print("--- Chuẩn bậc 1000 ---")
print(f"chuan(a, 1000): {chuan(a, 1000)}")
print(f"np.linalg.norm(a, 1000): {np.linalg.norm(a, 1000)}")
print("-" * 30 + "\n")



print("--- Lưu ý về lỗi có thể xảy ra ---")
print("Hàm chuan(vector, p) được định nghĩa như trên sẽ hoạt động tốt với p dương.")
print("Nếu p không hợp lệ (ví dụ: p = 0 hoặc p âm), có thể gây ra lỗi.")
print("-" * 30 + "\n")

print("--- Sử dụng scipy.linalg.norm ---")
print(f"linalg.norm(a) (mặc định p=2): {linalg.norm(a)}")
print(f"linalg.norm(a, 100): {linalg.norm(a, 100)}")
print(f"linalg.norm(a, 1000): {linalg.norm(a, 1000)}")
print("-" * 30 + "\n")

Vector a: [ 1  2 -3]

--- Chuẩn bậc 1 (Manhattan Norm) ---
chuan(a, 1): 6.0
np.linalg.norm(a, 1): 6.0
------------------------------

--- Chuẩn bậc 2 (Euclidean Norm) ---
chuan(a, 2): 3.7416573867739413
np.linalg.norm(a, 2): 3.7416573867739413
------------------------------

--- Chuẩn bậc 3 ---
chuan(a, 3): 3.3019272488946263
np.linalg.norm(a, 3): 3.3019272488946263
------------------------------

--- Chuẩn bậc 1000 ---
chuan(a, 1000): nan
np.linalg.norm(a, 1000): inf
------------------------------

--- Lưu ý về lỗi có thể xảy ra ---
Hàm chuan(vector, p) được định nghĩa như trên sẽ hoạt động tốt với p dương.
Nếu p không hợp lệ (ví dụ: p = 0 hoặc p âm), có thể gây ra lỗi.
------------------------------

--- Sử dụng scipy.linalg.norm ---
linalg.norm(a) (mặc định p=2): 3.7416573867739413
linalg.norm(a, 100): 3.0
linalg.norm(a, 1000): inf
------------------------------



C:\Users\Admin\AppData\Local\Temp\ipykernel_7192\710656131.py:17: RuntimeWarning: invalid value encountered in power
  return np.sum(np.abs(vector)**p)**(1/p)
C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\numpy\linalg\linalg.py:2549: RuntimeWarning: overflow encountered in power
  absx **= ord


### 2. Đọc thêm: Tổ hợp tuyến tính
#### Tổ hợp tuyến tính (linear combination)

In [8]:
import numpy as np

# Khởi tạo các biến và vector
m = 10
v1 = np.array([5,-4,3])
v2 = np.array([4,3,-2])
v3 = np.array([-4,-3,-1])
v4 = np.array([-9,8,6])
mi = np.array([2,5,2,1])

# Tạo ma trận M từ các vector hàng
M = np.array([v1,v2,v3,v4])
print("Ma trận M:")
print(M)
print("-" * 30 + "\n")

# Chuyển vị của Ma trận M (MT)
MT = M.transpose()
print("Ma trận chuyển vị MT:")
print(MT)
print("-" * 30 + "\n")

# Tính toán Vector v
v = (1.0/m) * MT.dot(mi)

# In kết quả của vector v
print("Vector v:")
print(v)
print("-" * 30 + "\n")

Ma trận M:
[[ 5 -4  3]
 [ 4  3 -2]
 [-4 -3 -1]
 [-9  8  6]]
------------------------------

Ma trận chuyển vị MT:
[[ 5  4 -4 -9]
 [-4  3 -3  8]
 [ 3 -2 -1  6]]
------------------------------

Vector v:
[1.3 0.9 0. ]
------------------------------



#### 3. Tri riêng, vector riêng của ma trận và ứng dụng
##### 3.1.Bài toán dẫn nhập 

In [9]:
import numpy as np

# Khai báo ma trận A
A = np.array([[0.998, 0.136],
              [0.002, 0.864]])

# Khai báo vector v0
v0 = np.array([0.95, 0.05])

# Tính vector A^100
A_power_100 = np.linalg.matrix_power(A, 100)

# Tính vector x100 và y100
v100 = A_power_100 @ v0

# In kết quả
print(f"{v100}")

[0.98550723 0.01449277]


#### Trạng thái cân bằng (Markov)

In [10]:
import numpy as np
import sympy as sym

# --- Phần giải bằng NumPy ---
# Khai báo ma trận hệ số B
B = np.array([[1, -68],
              [1, 1]])

# Khai báo vector vế phải c
c = np.array([0, 1])

# Giải hệ phương trình B * [x, y]T = c
solution_np = np.linalg.solve(B, c)

print("Giải pháp bằng NumPy (x, y):")
print(solution_np)
print("-" * 50)

# --- Phần giải bằng SymPy ---
# Khai báo biến ký hiệu
x, y = sym.symbols('x y')

# Khai báo vector biến
xy = sym.Matrix([x,y])

# Khai báo ma trận hệ số cho SymPy
A_sym = sym.Matrix([[1, -68],[1,1]])

# Khai báo vector vế phải cho SymPy
v_sym = sym.Matrix([0, 1])

# Giải hệ phương trình A_sym * xy - v_sym = 0
nghiem = sym.solve(A_sym * xy - v_sym)

# In kết quả SymPy
print("Giải pháp bằng SymPy:")
print(sym.pretty(nghiem))


Giải pháp bằng NumPy (x, y):
[0.98550725 0.01449275]
--------------------------------------------------
Giải pháp bằng SymPy:
⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭


##### 3.2.Trị riêng và vector riêng của ma trận

In [11]:
import numpy as np
import sympy as sym

A = np.array([[5, 6],
              [5, 2]])

# Khai báo vector riêng u
u = np.array([1, -5])

# Tính Au
Au = A @ u

# Tính -4u
neg4u = -4 * u

print("Ma trận A:\n", A)
print("\nVector u:\n", u)
print("\nAu:\n", Au)
print("\n-4u:\n", neg4u)

# So sánh Au và -4u
# np.allclose là tốt hơn np.array_equal cho số thực do vấn đề sai số dấu phẩy động
if np.allclose(Au, neg4u):
    print("\nAu = -4u: Phát biểu ĐÚNG.")
else:
    print("\nAu = -4u: Phát biểu SAI.")

print("-" * 50)


# Khai báo biến ký hiệu cho trị riêng (lambda)
lambda_sym = sym.symbols('lambda')

# Khai báo ma trận A trong SymPy (để làm việc với ký hiệu)
A_sym = sym.Matrix([[5, 6],
                    [5, 2]])

# Khai báo ma trận đơn vị I cùng kích thước với A_sym
I_sym = sym.eye(A_sym.shape[0])

# Tính ma trận (A - lambda*I)
A_minus_lambda_I = A_sym - lambda_sym * I_sym
print("\nMa trận (A - lambda*I):\n", sym.pretty(A_minus_lambda_I))

# Tính định thức của (A - lambda*I)
determinant = A_minus_lambda_I.det()
print("\nĐịnh thức |A - lambda*I|:\n", sym.pretty(determinant))

# Giải phương trình định thức = 0 để tìm trị riêng
eigenvalues_sym = sym.solve(determinant, lambda_sym)
print("\nTrị riêng (Eigenvalues) từ SymPy solve:\n", eigenvalues_sym)

print("-" * 50)

# 2. Sử dụng NumPy để tính trị riêng (kiểm tra lại)
eigenvalues_np, eigenvectors_np = np.linalg.eig(A)
print("\nTrị riêng (Eigenvalues) từ NumPy np.linalg.eig:\n", eigenvalues_np)
print("\nVector riêng (Eigenvectors) từ NumPy np.linalg.eig (cột tương ứng với trị riêng):\n", eigenvectors_np)

Ma trận A:
 [[5 6]
 [5 2]]

Vector u:
 [ 1 -5]

Au:
 [-25  -5]

-4u:
 [-4 20]

Au = -4u: Phát biểu SAI.
--------------------------------------------------

Ma trận (A - lambda*I):
 ⎡5 - λ    6  ⎤
⎢            ⎥
⎣  5    2 - λ⎦

Định thức |A - lambda*I|:
  2           
λ  - 7⋅λ - 20

Trị riêng (Eigenvalues) từ SymPy solve:
 [7/2 - sqrt(129)/2, 7/2 + sqrt(129)/2]
--------------------------------------------------

Trị riêng (Eigenvalues) từ NumPy np.linalg.eig:
 [ 9.17890835 -2.17890835]

Vector riêng (Eigenvectors) từ NumPy np.linalg.eig (cột tương ứng với trị riêng):
 [[ 0.82058481 -0.64129241]
 [ 0.57152478  0.76729658]]


In [12]:
import sympy

# Khai báo các biến ký hiệu
x, y, Lambda = sympy.symbols('x y Lambda')

# Khai báo ma trận đơn vị I
I = sympy.eye(2)

# Khai báo ma trận A
A = sympy.Matrix([[2,3],[3,-6]])

# Xây dựng phương trình đặc trưng: det(Lambda*I - A) = 0
phuongtrinh = sympy.Eq(sympy.det(Lambda*I - A), 0)

# Giải phương trình để tìm trị riêng
nghiem = sympy.solve(phuongtrinh)

# In kết quả với 4 chữ số có nghĩa
print([sympy.N(phantu,4) for phantu in nghiem])

# In kết quả theo định dạng đẹp của SymPy
print (sympy.pretty(nghiem))

[-7.000, 3.000]
[-7, 3]


In [13]:
import sympy as sym

# Khai báo các biến ký hiệu
x, y = sym.symbols('x y')

# Khai báo ma trận A
A = sym.Matrix([[2, 3],
                [3, -6]])

# Khai báo trị riêng Lambda (ví dụ với Lambda = 3)
Lambda = 3

# Khai báo ma trận đơn vị I
I = sym.eye(2)

# Xây dựng ma trận (A - Lambda*I)
A_minus_Lambda_I = A - Lambda * I

# Khai báo vector biến v
v = sym.Matrix([x, y])

# Xây dựng hệ phương trình (A - Lambda*I) * v = 0
equations = A_minus_Lambda_I * v

# Giải hệ phương trình
eigenvector_solution = sym.solve(equations, (x, y))

# In kết quả
print(f"Ma trận (A - Lambda*I):\n{sym.pretty(A_minus_Lambda_I)}")
print(f"\nHệ phương trình (A - Lambda*I)v = 0:\n{sym.pretty(equations)}")
print(f"\nGiải pháp cho vector riêng (x, y) khi Lambda = {Lambda}:\n{sym.pretty(eigenvector_solution)}")

Ma trận (A - Lambda*I):
⎡-1  3 ⎤
⎢      ⎥
⎣3   -9⎦

Hệ phương trình (A - Lambda*I)v = 0:
⎡-x + 3⋅y ⎤
⎢         ⎥
⎣3⋅x - 9⋅y⎦

Giải pháp cho vector riêng (x, y) khi Lambda = 3:
{x: 3⋅y}


#### 3.3.Ứng dụng của trị riêng và vector riêng

In [ ]:
import numpy as np
from numpy import linalg as LA

# Khai báo ma trận A, D, P
A = np.array([[2, 3],
              [3, -6]])

D = np.array([[-7, 0],
              [0, 3]]) gg4gg4

P = np.array([[-1.0/3, 3],
              [1, 1]])

# Tính P^(-1)
P1 = LA.inv(P)
print(P1)

# Kiểm tra A.dot(P)
print(A.dot(P))

# Kiểm tra P.dot(D)
print(P.dot(D))

# Tính A^1000
A_power_1000 = P @ (D ** 1000) @ P1
print(A_power_1000)

# Thử tính các giá trị lũy thừa của ma trận đường chéo
print(D ** 2)

[[-0.3  0.9]
 [ 0.3  0.1]]
[[ 2.33333333  9.        ]
 [-7.          3.        ]]
[[ 2.33333333  9.        ]
 [-7.          3.        ]]
[[-6.25396533e+08 -3.52488701e+08]
 [-3.52488701e+08  3.14573335e+08]]
[[49  0]
 [ 0  9]]


#### BT Chương 6

In [ ]:
#câu1
import numpy as np
a = np.array([1,2,3])

# Cách phổ biến và hiệu quả nhất
mag_norm = np.linalg.norm(a) 
print(f"Sử dụng np.linalg.norm: {mag_norm}")

# Kiểm tra các lựa chọn khác
mag_a = np.sqrt(a.dot(a))
print(f"Lựa chọn a: {mag_a}")

mag_b = np.sqrt(a @ a)
print(f"Lựa chọn b: {mag_b}")

mag_c = np.sqrt(np.inner(a, a))
print(f"Lựa chọn c: {mag_c}")

import math
mag_d_func = lambda x : math.sqrt(sum(i** 2 for i in x))
mag_d = mag_d_func(a)
print(f"Lựa chọn d: {mag_d}")

Sử dụng np.linalg.norm: 3.7416573867739413
Lựa chọn a: 3.7416573867739413
Lựa chọn b: 3.7416573867739413
Lựa chọn c: 3.7416573867739413
Lựa chọn d: 3.7416573867739413


In [ ]:
import numpy as np

# Câu 2a: Tính khoảng cách giữa 2 vector u và v 
def calculate_distance(u, v):
    if len(u) != len(v):
        raise ValueError("Hai vector phải có cùng kích thước.")
    diff_vector = u - v
    distance = np.linalg.norm(diff_vector)
    return distance
vector_u_dist = np.array([1, 2, 3])
vector_v_dist = np.array([4, 5, 6])
dist = calculate_distance(vector_u_dist, vector_v_dist)
print(f"Khoảng cách: {dist}")
print("-" * 30)

# --- Câu 2b: Tính góc theta của 2 vector u và v ---
def calculate_angle(u, v):
    if len(u) != len(v):
        raise ValueError("Hai vector phải có cùng kích thước.")
    dot_product = np.dot(u, v)
    norm_u = np.linalg.norm(u)
    norm_v = np.linalg.norm(v)
    if norm_u == 0 or norm_v == 0:
        return np.nan
    cosine_theta = dot_product / (norm_u * norm_v)
    cosine_theta = np.clip(cosine_theta, -1.0, 1.0) # Đảm bảo giá trị trong [-1, 1]
    angle_rad = np.arccos(cosine_theta)
    return angle_rad
vector_u_angle = np.array([1, 0])
vector_v_angle = np.array([0, 1])
angle = calculate_angle(vector_u_angle, vector_v_angle)
print(f"Góc (radian): {angle}")
print("-" * 30)

# --- Câu 2c: Phép chiếu trực giao p của vector u lên v ---
def orthogonal_projection(u, v):
    if len(u) != len(v):
        raise ValueError("Hai vector phải có cùng kích thước.")
    dot_uv = np.dot(u, v)
    dot_vv = np.dot(v, v)
    if dot_vv == 0:
        return np.zeros_like(v)
    scalar_factor = dot_uv / dot_vv
    projection = scalar_factor * v
    return projection
vector_u_proj = np.array([1, 2])
vector_v_proj = np.array([3, 0])
proj = orthogonal_projection(vector_u_proj, vector_v_proj)
print(f"Phép chiếu: {proj}")
print("-" * 30)

Khoảng cách: 5.196152422706632
------------------------------
Góc (radian): 1.5707963267948966
------------------------------
Phép chiếu: [1. 0.]
------------------------------
